### ISSUE TITLE
feat: auto paste api url

### ISSUE THREAD

**Issue by qingwan123** [lollipopkit/flutter_gpt_box#108]
就是在添加新的api配置后，秘钥和api地址任然保留着上一个api配置的参数，需要手动删除再填。虽然不影响但是希望完善下。

![Screenshot_2024-07-22-16-35-48-501_tech.lolli.flutter_gpt.jpg](https://github.com/user-attachments/assets/0ba262e2-6aea-4df7-b7a2-f410ad478c2c)

**Comment by lollipopkit** [comment]
这是前几天才新加的 feature...

**Comment by qingwan123** [comment]
好吧，可能跟我理解的新建不同，我以为添加新的配置就会是空白的呢

**Comment by lollipopkit** [comment]
可以自动读取剪切板，如果是链接，自动填充 url

**Comment by lollipopkit** [comment]
Implemented, please wait for release or test [beta](https://cdn.lolli.tech/gptbox/pkg/)
