### ISSUE TITLE
deepseek的beta版连不上

换了这个url刷新不出来

### ISSUE THREAD

**Issue by luoxiashen** [lollipopkit/flutter_gpt_box#114]
![Screenshot_2024-07-26-23-35-58-943_mark.via.jpg](https://github.com/user-attachments/assets/d1ab1eff-eb5f-4445-b10c-a09f93a14acc)
![Screenshot_2024-07-26-23-37-35-517_tech.lolli.flutter_gpt.jpg](https://github.com/user-attachments/assets/767863f4-dc5e-4308-8b1b-b8b91653fb99)

**Comment by lollipopkit** [comment]
<img width="390" alt="image" src="https://github.com/user-attachments/assets/0393c1bb-64e4-47b5-8786-5c45d319439b">

是网站 404，接口不标准，等官方进入稳定版吧
