### ISSUE TITLE
这个是bug吗
不能连续对话，删掉上面图片又恢复正常

### ISSUE THREAD

**Issue by luoxiashen** [lollipopkit/flutter_gpt_box#156]
![Screenshot_2024-08-15-11-06-01-116_tech.lolli.flutter_gpt.jpg](https://github.com/user-attachments/assets/cf817d87-be12-488a-b685-51220f827f40)

![Screenshot_2024-08-15-11-06-05-430_tech.lolli.flutter_gpt.jpg](https://github.com/user-attachments/assets/c85fc5fe-a028-4d3a-8070-5d47db306852)

**Comment by lollipopkit** [comment]
#75 重复

我的问题，会尽快解决
