### ISSUE TITLE
https://models.inference.ai.azure.com/chat/completions/

### ISSUE THREAD

**Issue by alphavvv** [lollipopkit/flutter_gpt_box#162]
由于github models的地址是https://models.inference.ai.azure.com/chat/completions/ 路径不包括v1 目前加进去无法使用 希望可以考虑类似ios chatx那样支持配置url路径 或者其他解决方式

**Comment by lollipopkit** [comment]
Implemented in 45ef71c9765fe259fb9640ee5cd22b0e23b1478e

**Comment by lollipopkit** [comment]
已支持，将在下次更新后可用
