### ISSUE TITLE
无法识别github model中的模型，只能手动自定义

### ISSUE THREAD

**Issue by vimbackground** [lollipopkit/flutter_gpt_box#173]
**描述BUG**

安装了新版的gptbox，设置url和配置时，用的github model。填写后无法自动识别出模型，只能手动自定义录入“gpt-4o”或者“gpt-4o-mini”，且使用不了github的其它模型（如command-r、ollama3等）

而在cherry studio同样的key，可以添加的模型有许多。

想确认一下这是不是一个bug，还是gptbox目前确实只能使用github的gpt模型？

如果是前者，希望能有个解决方案；如果是后者，那就没事了，先这样用着吧，希望后续能更完善。

**截图**

![gptbox](https://github.com/user-attachments/assets/d45f67b8-b8c3-4499-9bd9-125b88bdd11d)

![cherry](https://github.com/user-attachments/assets/78ec7d55-0228-4dbd-bb3b-0be426bf4246)

**设备**

win版和android版情况一样。

**Comment by lollipopkit** [comment]
模型列表无法获取是 GitHub models 的 API 与 openai 不同，已兼容

![IMG_4400](https://github.com/user-attachments/assets/9e85df67-e6f5-49d7-a61f-44060238c2f6)

**Comment by vimbackground** [comment]
谢谢，期待新版下载
