### ISSUE TITLE
当我关闭自动换行，无法左右滑动查看代码块

### ISSUE THREAD

**Issue by CHEN1016** [lollipopkit/flutter_gpt_box#62]
当我关闭自动换行，无法左右滑动查看代码块

- 系统： IOS17.3.1
- App版本： v1.0.233

**Comment by lollipopkit** [comment]
暂时的解决方案：双指拖动

**Comment by lollipopkit** [comment]
已修复，请等待发布更新

**Comment by lollipopkit** [comment]
<img width="935" alt="image" src="https://github.com/lollipopkit/flutter_gpt_box/assets/10864310/13388462-86f4-477d-b9ea-465bb7339627">
你果效率真高👍
