### ISSUE TITLE
windows 无法下载

### ISSUE THREAD

**Issue by 52sanmao** [lollipopkit/flutter_gpt_box#7]
下载Windows端的链接点击访问被拒绝：

![image](https://github.com/lollipopkit/flutter_gpt_box/assets/56877770/ae530653-0cbe-46f0-9916-f52b3e4639df)

**Comment by lollipopkit** [comment]
因为仍在开发中，所以暂未提供

**Comment by lollipopkit** [comment]
已可以下载体验

https://cdn.lolli.tech/gptbox/GPTBox_127.win.zip
