### ISSUE TITLE
BUG: Unable to generate images (does not switch models)

### ISSUE THREAD

**Issue by eyv** [lollipopkit/flutter_gpt_box#73]
**描述BUG**

When selecting "Image" at the bottom right of the chat window, the model text switches appropriately under the chat title (e.g., from gpt-4o to dall-e-3. However, it seems like the API call is still trying to use the text model. This is the return from the server for any image generation request:

(GPT-4 generated translation:
在聊天窗口的右下角选择“图像”时，聊天标题下的模型文本会相应切换（例如，从gpt-4o切换到dall-e-3）。然而，看起来API调用仍然尝试使用文本模型。以下是服务器对任何图像生成请求的返回：)

```
Error: RequestFailedException(message: Invalid model gpt-4o. The model argument should be left blank., statusCode: 400)

Trace:
#0      OpenAINetworkingClient.post (package:dart_openai/src/core/networking/client.dart:332)
<asynchronous suspension>
#1      OpenAIImages.create (package:dart_openai/src/instance/images/images.dart:89)
<asynchronous suspension>
#2      _onCreateImg (package:gpt_box/view/page/home/req.dart:292)
<asynchronous suspension>
#3      _onCreateRequest (package:gpt_box/view/page/home/req.dart:66)
<asynchronous suspension>
```

![IMG_5720](https://github.com/lollipopkit/flutter_gpt_box/assets/101942/e456c40e-2641-4dfc-83c2-4cf2d4c300f9)

**Log**
[19:10][App][INFO]
Using default profile

[19:10][App][WARNING]
Create image: RequestFailedException (message: Invalid model gpt-4o. The model argument should be left blank., statusCode: 400)

[19:11[App][WARNING]
Create image: RequestFailedException(message: Invalid model gpt-4o. The model argument should be left blank., statusCode: 400)

[19:11][App][|NFO]
Update ignored: 240 >= 215

设备: iPhone 14 Pro
系统: iOS 17.5.1
App版本: 1.0.240 (but the issue is not new — I've been having it since I downloaded the app a month ago)

**Comment by lollipopkit** [comment]
Plz wait for AppStore to approve. If this issue persists, open a new one.
