### ISSUE TITLE
gpt-4o的图片连续对话报错

### ISSUE THREAD

**Issue by Mgrsc** [lollipopkit/flutter_gpt_box#75]
gpt-4o的图片连续对话报错
![5E2392009B511B83001A57FE859E12D3](https://github.com/lollipopkit/flutter_gpt_box/assets/118801216/fee0b2a4-7913-4aac-ae4d-0dbfdd9cca10)
已在其他平台测试正常，排除api问题
![image](https://github.com/lollipopkit/flutter_gpt_box/assets/118801216/ce1f5fb7-a01d-4b7a-8755-fabee5e8919d)

**Comment by luoxiashen** [comment]
我今天也遇到了

下面是报错信息：
Error: RequestFailedException(message: 模型无返回结果，可能是内容违规、输入过长、输入格式有误或负载较高，请检查后再试。No response, please try again., statusCode: 503)

Trace:
``````

**Comment by lollipopkit** [comment]
![e687e263a11d056bff9d0ee506c93842](https://github.com/user-attachments/assets/dbac9493-2a77-4ba9-909a-4f53980f5d6d)
