### ISSUE TITLE
api余额查询

### ISSUE THREAD

**Issue by luoxiashen** [lollipopkit/flutter_gpt_box#82]
可以添加这个功能吗，好像不同的api查询的方式都不一样，可以考虑加个快捷方式之类的。或者增加几个主流的api余额查询（比如gpt-api-free：https://api.chatanywhere.tech/#/            
，和官方）

**Comment by lollipopkit** [comment]
官方文档内没有找到查询接口，目前新增了：deepseek、chatanywhere。

oneapi 实现较为麻烦，暂时搁置
