### ISSUE TITLE
chatanywhere余额查询不出来

### ISSUE THREAD

**Issue by luoxiashen** [lollipopkit/flutter_gpt_box#93]
deepk正常
![Screenshot_2024-07-19-08-10-11-650_tech.lolli.flutter_gpt.jpg](https://github.com/user-attachments/assets/b2f557b0-f7ce-463b-aa77-0f49a7c92cd9)

**Comment by lollipopkit** [comment]
可能是我是免费账户，如果可以麻烦私聊提供 api key
